import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/provider/context";
import { NotificationProvider } from "@/provider/notification";
import QueryProvider from "@/provider/query";
import ErrorBoundary from "./components/ErrorBoundary";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary>
          <QueryProvider>
            <SocketProvider>
              <NotificationProvider>{children}</NotificationProvider>
            </SocketProvider>
          </QueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
